In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [8]:
df=pd.read_csv("/content/drive/MyDrive/ML Projects/homeprices_multiple_var.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [12]:
#Data Pre Processing
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [17]:
# Replace NaN value with median
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [18]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [22]:
# price = m1*area +m2*bedrooms + m3*area + b
reg.coef_
#below are values of m1,m2,m3

array([  112.06244194, 23388.88007794, -3231.71790863])

In [21]:
reg.intercept_

221323.00186540396

In [23]:
reg.predict([[3000,3,25]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([546884.0202098])

In [28]:
#Recheck
112.06244194*3000 + 23388.88007794*3 - 3231.71790863*25 + 221323.00186540396
#working 👌

546884.020203474

In [27]:
reg.predict([[2500,4,5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])